// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protos/definitions.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebugMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugMessage) Reset() {
	*x = DebugMessage{}
	mi := &file_protos_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugMessage) ProtoMessage() {}

func (x *DebugMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugMessage.ProtoReflect.Descriptor instead.
func (*DebugMessage) Descriptor() ([]byte, []int) {
	return file_protos_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *DebugMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScheduleTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleType  []*ScheduleType        `protobuf:"bytes,1,rep,name=scheduleType,proto3" json:"scheduleType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTypes) Reset() {
	*x = ScheduleTypes{}
	mi := &file_protos_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTypes) ProtoMessage() {}

func (x *ScheduleTypes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTypes.ProtoReflect.Descriptor instead.
func (*ScheduleTypes) Descriptor() ([]byte, []int) {
	return file_protos_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleTypes) GetScheduleType() []*ScheduleType {
	if x != nil {
		return x.ScheduleType
	}
	return nil
}

type ScheduleType struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScheduleTypeName string                 `protobuf:"bytes,1,opt,name=scheduleTypeName,proto3" json:"scheduleTypeName,omitempty"`
	ScheduleTpeId    string                 `protobuf:"bytes,2,opt,name=scheduleTpeId,proto3" json:"scheduleTpeId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScheduleType) Reset() {
	*x = ScheduleType{}
	mi := &file_protos_definitions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleType) ProtoMessage() {}

func (x *ScheduleType) ProtoReflect() protoreflect.Message {
	mi := &file_protos_definitions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleType.ProtoReflect.Descriptor instead.
func (*ScheduleType) Descriptor() ([]byte, []int) {
	return file_protos_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleType) GetScheduleTypeName() string {
	if x != nil {
		return x.ScheduleTypeName
	}
	return ""
}

func (x *ScheduleType) GetScheduleTpeId() string {
	if x != nil {
		return x.ScheduleTpeId
	}
	return ""
}

var File_protos_definitions_proto protoreflect.FileDescriptor

const file_protos_definitions_proto_rawDesc = "" +
	"\n" +
	"\x18protos/definitions.proto\"(\n" +
	"\fdebugMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\rScheduleTypes\x121\n" +
	"\fscheduleType\x18\x01 \x03(\v2\r.ScheduleTypeR\fscheduleType\"`\n" +
	"\fScheduleType\x12*\n" +
	"\x10scheduleTypeName\x18\x01 \x01(\tR\x10scheduleTypeName\x12$\n" +
	"\rscheduleTpeId\x18\x02 \x01(\tR\rscheduleTpeId2=\n" +
	"\x0fScheduleScraper\x12*\n" +
	"\n" +
	"GetMessage\x12\r.debugMessage\x1a\r.debugMessageB\x1bZ\x19go_schedule_server/protosb\x06proto3"

var (
	file_protos_definitions_proto_rawDescOnce sync.Once
	file_protos_definitions_proto_rawDescData []byte
)

func file_protos_definitions_proto_rawDescGZIP() []byte {
	file_protos_definitions_proto_rawDescOnce.Do(func() {
		file_protos_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_definitions_proto_rawDesc), len(file_protos_definitions_proto_rawDesc)))
	})
	return file_protos_definitions_proto_rawDescData
}

var file_protos_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_definitions_proto_goTypes = []any{
	(*DebugMessage)(nil),  // 0: debugMessage
	(*ScheduleTypes)(nil), // 1: ScheduleTypes
	(*ScheduleType)(nil),  // 2: ScheduleType
}
var file_protos_definitions_proto_depIdxs = []int32{
	2, // 0: ScheduleTypes.scheduleType:type_name -> ScheduleType
	0, // 1: ScheduleScraper.GetMessage:input_type -> debugMessage
	0, // 2: ScheduleScraper.GetMessage:output_type -> debugMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_definitions_proto_init() }
func file_protos_definitions_proto_init() {
	if File_protos_definitions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_definitions_proto_rawDesc), len(file_protos_definitions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_definitions_proto_goTypes,
		DependencyIndexes: file_protos_definitions_proto_depIdxs,
		MessageInfos:      file_protos_definitions_proto_msgTypes,
	}.Build()
	File_protos_definitions_proto = out.File
	file_protos_definitions_proto_goTypes = nil
	file_protos_definitions_proto_depIdxs = nil
}
